baseURL = "https://derbur.github.io/hugo-demo/"
languageCode = "en-us"
title = "hugo-demo"
theme = "hugo-theme-codex"

[params]
  twitter = "https://twitter.com/_derbur"
  github = "https://github.com/derbur"
  linkedin = "https://www.linkedin.com/in/thederrickburns/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/"
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/blog"
